//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace MyTaskOrg.Models
{
    using System;
    using System.Data.Entity;
    using System.Data.Entity.Infrastructure;
    
    public partial class MyTaskDataEntities1 : DbContext
    {
        public MyTaskDataEntities1()
            : base("name=MyTaskDataEntities1")
        {
        }
    
        protected override void OnModelCreating(DbModelBuilder modelBuilder)
        {
            throw new UnintentionalCodeFirstException();
        }
    
        public virtual DbSet<adminTable> adminTables { get; set; }
        public virtual DbSet<courseTable> courseTables { get; set; }
        public virtual DbSet<pictTable> pictTables { get; set; }
        public virtual DbSet<projectTable> projectTables { get; set; }
        public virtual DbSet<ClientTable> ClientTables { get; set; }
    }
}
